language: python
python:
  - "3.6"

install:    
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database grocerydeliverytest;' -U postgres

services:
  - postgresql

addons:
  postgresql: "10"

script:    
  - pytest --cov=app/api

after_success:
  - codeclimate-test-reporter